### ISSUE TITLE
Shuttle seems to have missed crediting further funds

### ISSUE THREAD

**Issue by StrathCole** [terra-money/shuttle#108]
@javiersuweijie it seems shuttle is missing some txs again. I have not researched all, but e.g. this one was reported 
https://etherscan.io/tx/0x8728ff36a23c7f69b0811706019dda9b0135d2454bc0e6d7ecc6eab348fb711d

**Comment by ghost** [comment]
Hi, the same issue has occured to me.

I've used the shuttle bridge many times before without any issues, but I didn't receive my unwrapped tokens this time.

Transaction Hash:
0xa84bc8238632fd3769dc8a924bf1c72a48f362c163051099d0497e1b76e80aaa

Edit: I've now received my coins. Thanks to TFL for fixing the bridge.

**Comment by Rysher23** [comment]
@javiersuweijie This also occurred for me for one of the approximately 10 txs I processed.  Here is the transaction hash:

https://etherscan.io/tx/0x4ff127b8f28b030f613e2db62fca240bd522b2c535bab1666adbe484aa392102

Thanks

**Comment by javiersuweijie** [comment]
This transaction matches this: https://etherscan.io/tx/0x8728ff36a23c7f69b0811706019dda9b0135d2454bc0e6d7ecc6eab348fb711d 

https://finder.terraclassic.community/mainnet/tx/e7cd6a1617e64b068bdbeb99b019a3b94f9b356e6068f4ec82c88bdedd7a8c58

**Comment by javiersuweijie** [comment]
https://etherscan.io/tx/0x4ff127b8f28b030f613e2db62fca240bd522b2c535bab1666adbe484aa392102

This is republished

**Comment by ghost** [comment]
> https://etherscan.io/tx/0x4ff127b8f28b030f613e2db62fca240bd522b2c535bab1666adbe484aa392102
> 
> This is republished

Shuttle has once again stopped unwrapping as of 15 hours ago after this transaction was sent.

**Comment by dinesh0304-2020** [comment]
It seems shuttle has missed my transactions. I bridged Lunc Coins to Terra Classic network from Ethereum, it’s been 36+ hours and I haven’t received my coins yet.

Find the transactions hash below:

0x4e82be1a0ece659e06364fdcda1c5abc6465bcbcdb99fb5d96333dc7c9ba517e

https://etherscan.io/tx/0x4e82be1a0ece659e06364fdcda1c5abc6465bcbcdb99fb5d96333dc7c9ba517e

0xe9a9310478f4609a108d408ac0ba21e4514c9024e82efbe549853bf9a761c433

https://etherscan.io/tx/0xe9a9310478f4609a108d408ac0ba21e4514c9024e82efbe549853bf9a761c433

Please check and help. Looking forward to hearing from you.

**Comment by javiersuweijie** [comment]
All the missing transactions are being broadcasted. Please check your transactions again.
