### ISSUE TITLE
Unwrapped LUNC not received 

### ISSUE THREAD

**Issue by Rysher23** [terra-money/shuttle#109]
Could someone look into this transaction where I unwrapped LUNC were not received.  This was the only transaction that experienced the issue.   

https://etherscan.io/tx/0x4ff127b8f28b030f613e2db62fca240bd522b2c535bab1666adbe484aa392102

Thanks

**Comment by javiersuweijie** [comment]
Hi, we will look into this and update this thread.

**Comment by Rysher23** [comment]
Thank you all!

-Adam

**Comment by devops-terra-money** [comment]
Republished here: https://finder.terraclassic.community/mainnet/tx/ADC024AE78A2DFFDDE04CD226283425367C8684533656B598FDEBD46FBE4C8B7
