### ISSUE TITLE
Migrate ETH tokens to Terra using Shuttle

### ISSUE THREAD

**Issue by chrisciszak** [terra-money/shuttle#21]
Hi guys,

We are trying to migrate permanently an ERC20 token to Terra CW20 token. We want to customize the Shuttle app to serve as a temporary bridge between the two environments. Obviously, in the current state, the Shuttle doesn't support Ethereum native tokens hence the need for customization.

The plan was to create a new contract on Ethereum where all the tokens would be locked and burnt. The Terra address would be provided to the function so once burnt has occurred and enough confirmations are available, we would mint the equivalent number of CW20 tokens and assign it to the address.

Could you point me in the right direction on how to go about it?

Thanks

**Comment by chrisciszak** [comment]
@YunSuk-Yeo any idea on the above?

**Comment by YunSuk-Yeo** [comment]
Oh sorry for delay. 

Yea as you mentioned, now the Shuttle does not have `ERC20` to `CW20` feature. That requires to implement followings:
- ERC20 lock monitoring & CW20 mint bot
- CW20 burn monitoring & ERC20 unlock bot

The important thing on this PoA bridge is who is the maintainer(= relayer), now the relayer is the Terra Foundation. But we can change this to multisig(already multisig) with other operators. Also we will implement reverse shuttle, if wormhole is not ready within few weeks.
