### ISSUE TITLE
How to be whitelisted?

### ISSUE THREAD

**Issue by tkowalczyk** [terra-money/shuttle#29]
Can you provide some guidelines for the project to be added to the whitelist?

How such process looks like? Looking forward for some clues and ready to pass any tests :)

**Comment by YunSuk-Yeo** [comment]
We need use cases to support the asset on the Shuttle. Can you say the asset you want to whitelist?

**Comment by tkowalczyk** [comment]
Thank you for your answer it will be $ST token from StarTerra.io project so we will probably contact later in this case.
