### ISSUE TITLE
Please add aUST to BSC.

### ISSUE THREAD

**Issue by octalmage** [terra-money/shuttle#30]
I've got an application that really needs aUST on the Binance Smart Chain. Please consider allowing users to bridge aUST over!

**Comment by YunSuk-Yeo** [comment]
We can whitelist the asset, can you say the use case?

**Comment by octalmage** [comment]
I'm running a Venture DAO based on BSC, and the DAO wants to invest our idle funds in Anchor. 

Thank you!

**Comment by wanyvic** [comment]
@YunSuk-Yeo  the same requirements, could you also add aUST on the BSC Testnet?
