### ISSUE TITLE
How to prepare contracts for Shuttle?

### ISSUE THREAD

**Issue by tkowalczyk** [terra-money/shuttle#31]
We would like to prepare our contracts to be whitelisted on Shuttle, where we can find some requirements for such process?

During my investigations I find out that we need contracts working on both blockchains:

- Terra - `CW20`
- Ethereum - `ERC20`

I have also analyzed source code for `ANC` (as a reference) smart contract to find out how to prepare for this task.

> please correct me if I'm wrong

From Terra blockchain side we need only standard `CW20` as Anchor mentiond on their GitHub repository that `ANC` depends on Terraswap `CW20` implementation - [source](https://github.com/anchor-protocol/anchor-token-contracts#anchor-token-anc-contracts). This contract address should be whitelisted?

From Ethereum blockchain side, based on [Wrapped ANC](https://etherscan.io/address/0x0F3ADC247E91c3c50bC08721355A41037E89Bc20#code) contract it looks like it should be enough to inherit from [WrappedToken.sol](https://github.com/terra-money/shuttle/blob/main/contracts/contracts/WrappedToken.sol) and this contract address should be whitelisted? 

Thanks in advance for any feedback

**Comment by ouiliame** [comment]
Hi -- what do you mean for your contracts to be whitelisted on Shuttle? Do you mean that you plan to release a dApp with cross-chain assets?

**Comment by tkowalczyk** [comment]
Yes, exactly. I would like to have tokens on both blockchains - Ethereum and Terra, so I would like to know how to prepare my smart contracts for this and have them whitelisted on Shuttle to be able to use on Terra Bridge.

**Comment by YunSuk-Yeo** [comment]
To be whitelisted, please do following items

## Terra token support
1. [Ethereum] Deploy WrappedToken Contract and do verify the contract code 
2. [Ethereum] Transfer ownership to proper minter address (minter address can be found in [here](../blob/main/TERRA_ASSET.md#erc20-contracts))

## Ethereum token support
1. [Ethereum] Deploy ShuttleVault contract like [vETH](../blob/main/contracts/vETH.sol) or [bETH](../blob/main/contracts/bETH.sol) with your ERC20 token address
2. [Ethereum] Transfer ownership to proper minter address (minter address can be found in [here](../blob/main/TERRA_ASSET.md#erc20-contracts))
3. [Terra] Deploy cw20 token contract by setting minter to tracking address (tracking address can be found in [here](../blob/main/TERRA_ASSET.md#terra--ethereum--bsc))
