### ISSUE TITLE
vulnerability

### ISSUE THREAD

**Issue by thinkingparticle** [terra-money/shuttle#35]
I can send 4 UST from terra to bridge and receive 3 UST in my eth wallet.
So I have paid 1$ in fee but the minting cost is around 4$ of for the minter, resulting in 3$ loss for the bridge cuz of eth spent. 
Might be a good idea to increase bridge fee a bit to atleast compensate the outbound transaction fee. Or increase the minimum bridgable amount.

**Comment by hanjukim** [comment]
I think it is rather a feature request not a vulnerability?

**Comment by thinkingparticle** [comment]
> I think it is rather a feature request not a vulnerability?

yea. not an actual vulnerability. I mean you are sponsoring the transactions. 
I can bridge 2 UST to ethereum but the bridge might pay 20$ eth gas fee to bridge my coins.
