### ISSUE TITLE
Bridge to harmony missing some transactions or sometimes too slow

### ISSUE THREAD

**Issue by thinkingparticle** [terra-money/shuttle#39]
There are cases where user funds doesn't bridge or takes a lot of time to bridge (+8 hours)

For example in case below the user hasn't received funds yet ton his terra wallet. 
https://explorer.harmony.one/tx/0x0e2b0ec53cabd57bd34f15b057c2d985bcc20ae255872798c1d40c57df80a548

His terra wallet address:
terra1wz0e773wymkzzxk6jvn0yvzftzhs8djes852t6

**Comment by YunSuk-Yeo** [comment]
here is recovery tx https://finder.terra.money/mainnet/tx/47e175c36648037037d8713e51eee10426548d7894599d2d5198cd86f6f71744

**Comment by thinkingparticle** [comment]
Thanks for fixing. sorry for reopening the issue. here is another missing tx of another user:
https://explorer.harmony.one/tx/0xb7a5c1428af24c146b2d0ac5f13a3e59b50dc934f31e23fc65ae9f282dcb5cf1

receiving wallet
terra1euv30vpxsjus2xs853x4kdgxctu3srvz3u6pe6
