### ISSUE TITLE
another missing transaction on terrabridge to harmony

### ISSUE THREAD

**Issue by thinkingparticle** [terra-money/shuttle#43]
Hi. this user has burned UST on harmony but hasn't received funds yet. appreciate if take a look. 
https://explorer.harmony.one/tx/0xb7a5c1428af24c146b2d0ac5f13a3e59b50dc934f31e23fc65ae9f282dcb5cf1

receiving wallet:
terra1euv30vpxsjus2xs853x4kdgxctu3srvz3u6pe6

**Comment by thinkingparticle** [comment]
Hi there. the above tx has bridge process has been stuck for around 7 days. I would appreciate it if you could process it or revert it. User a bit unhappy.

**Comment by YunSuk-Yeo** [comment]
recovered, https://finder.terra.money/mainnet/tx/55b13dc9d877d4e7f843e053026d351727b021cee175ffb1ae1deb36def25ff1

**Comment by thinkingparticle** [comment]
Sorry for re-opening. Looks like some transactions got stuck again when bridging to harmony.
For example this tx has been stuck more than a day:

https://finder.terra.money/columbus-5/tx/0F2E0897FA24A16D8A414E06B1D6C0E5F137BB06871D09ADC691C1483103E955
