### ISSUE TITLE
Terra shuttle contracts

### ISSUE THREAD

**Issue by deuszx** [terra-money/shuttle#44]
Hey team, where can I find Terra shuttle contracts? I can see Ethereum-side ones but not Terra's.

**Comment by iamshaho** [comment]
> 

Hi
there is 3 smart contract for Shuttle(main Terra bridge)
u can find them in Terra database in Velocity app.
there is a table for labels.filter it for bridge

**Comment by deuszx** [comment]
Thank you. I will look for that :)
