### ISSUE TITLE
tx stuck when bridging to harmony

### ISSUE THREAD

**Issue by thinkingparticle** [terra-money/shuttle#56]
Looks like some transactions got stuck again when bridging to harmony.
These transactions have not been processed:

https://finder.terra.money/mainnet/tx/0F2E0897FA24A16D8A414E06B1D6C0E5F137BB06871D09ADC691C1483103E955

https://finder.terra.money/mainnet/tx/820EDD6EDE361E3C5AB9823336A8ED90AA7FA987410DC33E0B83A8847BF2F1DE

https://finder.terra.money/mainnet/tx/060C8606356468D06ED35A56AD0928780680D081CF42D559C9E69DF33098457A

https://finder.terra.money/mainnet/tx/87ABC29EBE8E056ACC76F6CE18FC0649357517503499F589DB74C4C3B576F7A2

**Comment by robiso50** [comment]
Hello @thinkingparticle , A support ticket has been opened for you with Support ticket number TB7836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by thinkingparticle** [comment]
Ok now scammers are faster to address the problem than the team hehe. can you guys at least remove his scammy comment?

**Comment by YunSuk-Yeo** [comment]
Please join terra discord community for recovery.
btw harmony normally having problem, so we made auto recovery https://forms.gle/7qoLkEkummCZYtsJ9
