### ISSUE TITLE
UST transfer still not settled on Terra

### ISSUE THREAD

**Issue by DmytroShalaiev** [terra-money/shuttle#62]
I transfer UST from BSC to Terra
https://bscscan.com/tx/0x72163b94203e8811ea4141f3c15b45b9d275adfc3e52e94ce7e5117a9565f717
terra1hnzzq54nztcm2hlrw6pw5wzspl2v8hurdfdj6c
And my transfer still not arrived, any help please, what I should do?

**Comment by sammiyee** [comment]
> I transfer UST from BSC to Terra https://bscscan.com/tx/0x72163b94203e8811ea4141f3c15b45b9d275adfc3e52e94ce7e5117a9565f717 terra1hnzzq54nztcm2hlrw6pw5wzspl2v8hurdfdj6c And my transfer still not arrived, any help please, what I should do?

Hello, A support ticket has been opened for you with Support ticket number TBS8HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by BlankerL** [comment]
Hi, I am facing the same problem, did you get the funds?
